title: Ratul Dawar
description: Systems programming, performance optimization, and Rust experiments
theme: minima
url: "https://ratuldawar.github.io"
author: Ratul Dawar

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md

minima:
  social_links:
    - platform: github
      user_url: https://github.com/RatulDawar

sass:
  style: compressed
